// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNJP9IIeLjJjnywu9vhhguNJXsvojGRs',
    appId: '1:557642524488:web:1043e4186ab92240ebf57d',
    messagingSenderId: '557642524488',
    projectId: 'aptcodertask',
    authDomain: 'aptcodertask.firebaseapp.com',
    storageBucket: 'aptcodertask.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMz-xZwNFs_HnADifsF-oieTbscDMNDM',
    appId: '1:557642524488:android:d427888d462f1b10ebf57d',
    messagingSenderId: '557642524488',
    projectId: 'aptcodertask',
    storageBucket: 'aptcodertask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJNxe_W56z03CsNO_QpdaA4jBtMMSduKs',
    appId: '1:557642524488:ios:d276dde6a8194d91ebf57d',
    messagingSenderId: '557642524488',
    projectId: 'aptcodertask',
    storageBucket: 'aptcodertask.firebasestorage.app',
    iosBundleId: 'com.example.aptcoderApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJNxe_W56z03CsNO_QpdaA4jBtMMSduKs',
    appId: '1:557642524488:ios:d276dde6a8194d91ebf57d',
    messagingSenderId: '557642524488',
    projectId: 'aptcodertask',
    storageBucket: 'aptcodertask.firebasestorage.app',
    iosBundleId: 'com.example.aptcoderApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtNJP9IIeLjJjnywu9vhhguNJXsvojGRs',
    appId: '1:557642524488:web:5d44ccb4c53f60d0ebf57d',
    messagingSenderId: '557642524488',
    projectId: 'aptcodertask',
    authDomain: 'aptcodertask.firebaseapp.com',
    storageBucket: 'aptcodertask.firebasestorage.app',
  );
}
